@token = 4|PKSOsHNb470LfOn3H0nDwRytRlv1V9Sr3ZZO5knje29629de

###
GET http://localhost/api/authorization
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###
GET http://localhost/api/posts/home?page=1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###
GET http://localhost/api/posts/pins?page=1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###
POST http://localhost/api/posts/create
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer {{token}}

--boundary
Content-Disposition: form-data; name="comment"

APIから送信
--boundary
Content-Disposition: form-data; name="image"; filename="akunaki.png"
Content-Type: image/png

< public/akunaki.png
--boundary---


###
@id = 147
DELETE  http://localhost/api/posts/delete/{{ id }}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###
@pinId =152
PATCH   http://localhost/api/pins/pin/{{ pinId }}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###
PATCH   http://localhost/api/pins/unpin/{{ pinId }}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}
